# Generated by Django 3.1.2 on 2021-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210709_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('em_execucao', 'Em Execução'), ('finalizada', 'Finalizada')], default='registrada', max_length=20),
        ),
    ]
